version: '3.3'

services:
  node-express:
    build: .
    image: docker-node:dev
    container_name: node-dev5
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
